const UNICOURSE_ERROR_CODE_MESSAGES = {
  UNC001: 'Token has expired, please login again',
  UNC002: 'User already logged in another device',
  UNC003: 'User is blocked, please contact support for more information',
  UNC004: 'User account has been closed, please contact support for more information',
  UNC005: 'User is banned, with reason: ',
  UNC006: 'Invalid issuer signed, please login through the correct channel',
  UNC007: 'Vimeo access token is invalid',
  UNC008: 'Unauthorized access',
  UNC009: 'Refresh token has been revoked',
  UNC010: 'ID token has been revoked',
  UNC011: 'Account is on scheduling closed, please try again later',
  UNC012: 'Invalid refresh token, please login again',
  UNC013: 'Invalid access token, please login again',
  UNC014: 'Invalid password, please try again',
  UNC015: 'Access token is required',
  UNC016: 'Invalid token, please login again',
  UNC017: 'ID token is from 3rd party, please login through the correct channel',
  UNC050: 'Invalid permission, please contact support for more information',
  UNC051: 'Unsupported device type',
  UNC052: 'Resource access denied, please contact support for more information',
  UNC053: 'Role permission denied, please contact support for more information',
  UNC054: 'Device not verified, please verify your device',
  UNC055: 'Invalid local variable, please check your environment variables',
  UNC100: 'Internal server error, please try again later',
  UNC101: 'Server Database error, please try again later',
  UNC102: 'Rate limit exceeded, please try again later',
};

export { UNICOURSE_ERROR_CODE_MESSAGES };
